name: ci
on: [push, pull_request]
jobs:
  lint-disassemble-and-run:
    name: lint, disassemble and run example program
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm install
      - run: npm run lint
      - run: npm start programs/alphabet.synbin
      - run: npm start programs/self-modifying.synbin
