name: ci
on: [push, pull_request]
jobs:
  build:
    name: lint, disassemble and run example program
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm install
      - run: npm run lint
      - run: npm run disassemble example
      - run: npm start example
